# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ac60e568d32ea2c18ef1385fd9ca21e609f9854ac720a8fabd8bbbf74bb4c772489611f9fdc2065ca7e3ed8f47a59bf0be45ff7f83dfa79c697d0ad301b234f
  MAILCHIMP-API-KEY: "6772113f67bf7b7464d4ad034e2506d5-us10"
  MAILCHIMP-LIST-ID: "fa5fc6e674"

test:
  secret_key_base: 6b0851b2d2036a2ab884175f1b36eb647e57a6e4bdac5be3d38f6d8c08c6911072c183ff4e91fdd24842564367ccc1469a3566218fbb60072df2bfe4a83f1b7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  MAILCHIMP-API-KEY: "6772113f67bf7b7464d4ad034e2506d5-us10"
  MAILCHIMP-LIST-ID: "fa5fc6e674"
  # MAILCHIMP-API-KEY: <%= ENV["MAILCHIMP_API_KEY"] %>
